CREATE TABLE `TANK` (
 `TANK_ID` bigint(20) NOT NULL AUTO_INCREMENT,
 `TANK_TARGET_TEMP` int(11) NOT NULL,
 `TANK_SALINITY` decimal(7,4) NOT NULL,
 `TANK_SIZE` int(11) NOT NULL,
 `TANK_MONOCULTURE` int(11) NOT NULL,
 `TANK_NAME` varchar(50) NOT NULL,
 PRIMARY KEY (`TANK_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=43 DEFAULT CHARSET=latin1